### ISSUE TITLE
ActionSheet as a replacement for modal selector

### ISSUE THREAD

**Issue by dangnelson** [peacechen/react-native-modal-selector#42]
Came across this fork while hunting for a solution. Just thought I would offer a potential alternative...

`react-native-actionsheet` is very similar to this library, with the major visual missing feature being sections.

https://github.com/expo/react-native-action-sheet

**Comment by peacechen** [comment]
What are your thoughts on the functional and aesthetic differences between the two?  The live expo sample doesn't render for me.  Would help if they put up screenshots.

**Comment by dangnelson** [comment]
Whoops. That's a different repo with an identical name. Here's the one I'm currently using:
https://github.com/beefe/react-native-actionsheet

**Comment by peacechen** [comment]
react-native-actionsheet's Android implementation has a substantially different style than iOS.  iOS ActionSheet has rounded corners and a margin, whereas Android has none.

Personally I like react-native-modal-selector's pure JS implementation since that makes it possible to customize the look for both Android and iOS.

**Comment by dangnelson** [comment]
Makes sense. Just figured I'd throw it out there.
